// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVssQSHPEKO2FbqNN-u2HNB9hM8BdNfZo',
    appId: '1:1065813004622:web:c7603c5424b81842284e1f',
    messagingSenderId: '1065813004622',
    projectId: 'notes-flutter-myproject',
    authDomain: 'notes-flutter-myproject.firebaseapp.com',
    storageBucket: 'notes-flutter-myproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO0UlsSIhkcfzomOhTjouy0BeHMAaq_6o',
    appId: '1:1065813004622:android:d49264b56eee5521284e1f',
    messagingSenderId: '1065813004622',
    projectId: 'notes-flutter-myproject',
    storageBucket: 'notes-flutter-myproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdmCc0wQ8qDTxpuUjhgoFGodFMUvXasFU',
    appId: '1:1065813004622:ios:f20ac6e5b12f5e53284e1f',
    messagingSenderId: '1065813004622',
    projectId: 'notes-flutter-myproject',
    storageBucket: 'notes-flutter-myproject.appspot.com',
    iosClientId: '1065813004622-7mg0o9hdqsiv52glg3kl7b8lp8vmicdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdmCc0wQ8qDTxpuUjhgoFGodFMUvXasFU',
    appId: '1:1065813004622:ios:f20ac6e5b12f5e53284e1f',
    messagingSenderId: '1065813004622',
    projectId: 'notes-flutter-myproject',
    storageBucket: 'notes-flutter-myproject.appspot.com',
    iosClientId: '1065813004622-7mg0o9hdqsiv52glg3kl7b8lp8vmicdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesFlutter',
  );
}
